---
title: "citations.Rmd"
author: "Andrea Seisler"
date:  "`r Sys.time()`"
---

<!-- # Citation counts -->

```{r get-new-citations}
# Get citation counts from Google Scholar
get_citation_stats <- function(project = 'databrary') {
  if (project %in% c('databrary', 'Databrary')) {
    url <- 'https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22databrary%22&btnG='
  } else if (project %in% c('datavyu', 'Datavyu')) {
    url <- 'https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22datavyu%22&btnG='
  }
  
  r <- httr::GET(url = url)
  if (httr::status_code(r) == 200) {
    content <- httr::content(r, 'text')
  } else {
    message(paste0('Download Failed, HTTP status ', httr::status_code(r)))
  }
  
  n_results <- stringr::str_match(content, pattern = "About ([0-9]+)")[2]
  if (is.null(n_results)) {
    message(paste0('Unable to parse results from search.'))
    return(NULL)
  } else {
    return(as.numeric(n_results))
  }
}

databrary_cites <- get_citation_stats('databrary')
datavyu_cites <- get_citation_stats('datavyu')

old_citations <- citations <- read_csv("csv/citations-monthly.csv")
next_value <- dim(old_citations)[1] + 1
citations <- old_citations
citations[next_value,] <- NA

citations$date[next_value] <- Sys.Date()
citations$databrary_citations[next_value] <- databrary_cites
citations$datavyu_citations[next_value] <- datavyu_cites
```

```{r db-dv-citations-plot}
citations <- citations %>%
  gather(., key = "type", value = "count", -date)

# Plot
citations_plot <- 
  citations %>%
  ggplot(., aes(x = date, y = count, color = type, group = type)) +
  geom_point() + 
  geom_line(size = ln_size) +
  scale_colour_manual(values=c(color_orange, color_teal)) +
  ggtitle(paste("Citations as of ", Sys.Date())) +
  ylab("Citations") +
  databrary_theme +
 scale_y_continuous(breaks = seq(0, round_any(max(citations$count), 100, ceiling), 100), expand = c(0,0)) +
  coord_cartesian(ylim = c(0, round_any(max(citations$count), 100, ceiling)))
  
  
ggdraw(citations_plot) + 
  draw_label("Datavyu, ", colour = color_teal, .7, .5) +
  draw_label(max(datavyu_cites), colour = color_teal, .78, .5) +
  draw_label(max(databrary_cites), colour = color_orange, .79, .8) +
  draw_label("Databrary, ", colour = color_orange, .7, .8)
```

```{r update-citations-gs}
if (as.logical(params$update_gs)) {
  new_data <- data_frame(date = Sys.Date(), 
                         databrary_citations = databrary_cites, 
                         datavyu_citations = datavyu_cites)
  db <- db %>%
    gs_add_row(ws = 'citations-monthly', input = new_data)
  message("'update_gs' parameter is 'TRUE', so Google Sheet data will be updated.")
} else {
  message("'update_gs' parameter is 'FALSE', so Google Sheet data unmodified.")
}

```
