---
title: "Databrary Citations"
author: "Rick O. Gilmore"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    code_folding: hide
    self_contained: false
params:
  db_account: rogilmore@psu.edu
  update_stats: FALSE
  update_gs: FALSE 
---

# Set-up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(databraryapi)
library(tidyverse)
library(reshape2)
library(cowplot)

if (!databraryapi::login_db(params$db_account)) {
  message("Log-in failed.")
}

# Graphic theme elements
ln_size <- 3
base_size <- 14
color_orange <- "#ec7751"
color_teal <- "#4CAE99"

databrary_theme <- 
  theme_classic(base_size = base_size) +
  theme(axis.title.x=element_blank()) +
  theme(legend.position="none", 
        axis.text = element_text(size = rel(0.8), colour = "black")) +
  theme(axis.line = element_blank())
```

Set parameters for accessing Google sheet.

```{r data-from-googlesheets}
key <- "1tvlIQzULrMtXo97aJu71ljdTmNXkwwpU9eOOasVer3g"
db <- gs_title('Databrary-analytics')
```

Now, let's load the data about the number of institutions and investigators.

```{r load-inst-invest-from-googlesheets}
old_citations <- db %>%
  gs_read(ws = 'citations-monthly')
```

# Citation counts

```{r get-new-citations}
# Get citation counts from Google Scholar
get_citation_stats <- function(project = 'databrary') {
  if (project %in% c('databrary', 'Databrary')) {
    url <- 'https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22databrary%22&btnG='
  } else if (project %in% c('datavyu', 'Datavyu')) {
    url <- 'https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22datavyu%22&btnG='
  }
  
  r <- httr::GET(url = url)
  if (httr::status_code(r) == 200) {
    content <- httr::content(r, 'text')
  } else {
    message(paste0('Download Failed, HTTP status ', httr::status_code(r)))
  }
  
  n_results <- stringr::str_match(content, pattern = "About ([0-9]+)")[2]
  if (is.null(n_results)) {
    message(paste0('Unable to parse results from search.'))
    return(NULL)
  } else {
    return(as.numeric(n_results))
  }
}

databrary_cites <- get_citation_stats('databrary')
datavyu_cites <- get_citation_stats('datavyu')

# old_citations <- citations <- read_csv("csv/citations-monthly.csv")
# next_value <- dim(old_citations)[1] + 1
# citations <- old_citations
# citations[next_value,] <- NA
# 
# citations$date[next_value] <- Sys.Date()
# citations$databrary_citations[next_value] <- databrary_cites
# citations$datavyu_citations[next_value] <- datavyu_cites
```

```{r update-stats}
# initialize updated_stats
citations <- old_citations
if (as.logical(params$update_stats)) {
  next_entry <- dim(old_citations)[1] + 1
  citations[next_entry,] = NA
  
  # fill with new data
  citations$date[next_value] <- Sys.Date()
  citations$databrary_citations[next_value] <- databrary_cites
  citations$datavyu_citations[next_value] <- datavyu_cites
}
```

Next, we update the Google Sheet if `params$update_gs` is TRUE.

```{r update-gs}
if (as.logical(params$update_gs)) {
  db <- db %>%
    gs_add_row(ws = 'citations-monthly', input = citations[dim(citations)[1],1:3])
} else {
  message("'update_gs' parameter is 'false', so Google Sheet data unmodified.")
}
```

## Time series plot

```{r db-dv-citations-plot}
citations <- citations %>%
  gather(., key = "type", value = "count", -date)

# Plot
citations_plot <- 
  citations %>%
  ggplot(., aes(x = date, y = count, color = type, group = type)) +
  geom_point() + 
  geom_line(size = ln_size) +
  scale_colour_manual(values=c(color_orange, color_teal)) +
  ylab("Citations") +
  databrary_theme +
  scale_y_continuous(breaks = seq(0, 250, 50), expand = c(0,0)) +
  coord_cartesian(ylim = c(0, 250))
  
ggdraw(citations_plot) + 
  draw_label("Datavyu", colour = color_teal, .9, .6) +
  draw_label("Databrary", colour = color_orange, .7, .85)
```

## Citations as of `r Sys.Date()`

```{r summary-table}
citations %>%
  group_by(type) %>%
  filter(date == Sys.Date()) %>%
  summarize(citations = count) %>%
  knitr::kable()
```

