---
title: "volumes-shared"
author: "Andrea Seisler"
date:  "`r Sys.time()`"
---


```{r}
# Read from Google Sheet
old_vols <- db %>%
  gs_read(ws = 'volumes-shared-unshared')
```

<!-- Now update from information derived from `databraryapi::db_stats()` if `params$update_stats` is TRUE. -->

```{r update-volumes-data}
updated_vols <- old_vols
if (as.logical(params$update_stats)) {
  next_entry <- dim(updated_vols)[1] + 1
  updated_vols[next_entry,] = NA
  
  updated_vols$date[next_entry] <- new_stats$date
  if (is.null(new_stats$datasets_shared)) {
    new_stats$datasets_shared = 0
  }
  updated_vols$shared_volumes[next_entry] <- new_stats$datasets_shared
  updated_vols$unshared_volumes[next_entry] <- 
    new_stats$datasets_total - new_stats$datasets_shared
}
updated_vols <- updated_vols %>%
  gather(., key = "type", value = "count", -date)
```

```{r db-vols-plot}
# Plot
vols_plot <- updated_vols %>%
  ggplot(., aes(x = date, y = count, color = type, group = type)) +
  geom_point() + 
  geom_line(size=ln_size) +
  scale_colour_manual(values=c(color_orange, color_teal)) + 
  ggtitle(paste("Volumes as of ", Sys.Date())) +
  ylab("Volumes") +
  databrary_theme +
  scale_y_continuous(breaks = seq(0, round_any(max(updated_vols$count), 100, ceiling), 100), expand = c(0,0)) +
  coord_cartesian(ylim = c(0, round_any(max(updated_vols$count), 100, ceiling)))


ggdraw(vols_plot) + 
  draw_label("Unshared, ", colour = color_teal, .75, .85) +
  draw_label(max(new_stats$datasets_total - new_stats$datasets_shared), colour = color_teal, .84, .85) +
  draw_label(max(new_stats$datasets_shared), colour = color_orange, .72, .6) +
  draw_label("Shared, ", colour = color_orange, .65, .6)
```
<!-- Next, we update the Google Sheet if `params$update_gs` is TRUE. -->

```{r update-vols-shared-unshared}
if (as.logical(params$update_gs)) {
  new_data <- data_frame(date = Sys.Date(), 
                         shared_volumes = new_stats$datasets_shared, 
                         unshared_volumes = new_stats$datasets_total - new_stats$datasets_shared)
  db <- db %>%
    gs_add_row(ws = 'volumes-shared-unshared', input = new_data)  
} else {
  message("'update_gs' parameter is 'false', so Google Sheet data unmodified.")
}
```

## New volumes

```{r new-volumes}
# define helper functions
new_volumes <- databraryapi::get_db_stats(type = "datasets")
if (is.null(new_volumes)) {
  stop('New volumes data not downloaded.')
}

unnested_vols <- new_volumes %>%
  unnest(.)
  # rename(., owner_name = name1, owner_id = id1) %>%

unnested_vols$owner_name <- unnested_vols$name1
unnested_vols$owner_id = unnested_vols$name1 

# Change format of owner_name
char_split <- strsplit(unnested_vols$name1, ", ")
# mat  <- matrix(unlist(char_split, ncol=2, byrow=TRUE)) #Getting error in this line but it worked previously
# char_split   <- as.data.frame(mat)
# colnames(char_split) <- c("last_name", "first_name")
# char_split %>% unite(col = "full_name", first_name, last_name, sep=" ")
# char_split -> unnested_vols$owner_name


unnested_vols <- unnested_vols %>%
  mutate(., url = paste0("https://nyu.databrary.org/volume/", id),
         date_created = lubridate::as_date(creation))
  
unnested_vols %>%
  select(., name, date_created, owner_name, url) %>%
  knitr::kable(col.names = c("Volume Name", "Date Created", "Owner Name", "Databrary URL"))%>%
  kable_styling()
```