---
title: "Databrary Weekly"
author: "Rick O. Gilmore & Andrea Seisler"
date: "`r Sys.time()`"

output:
  html_document:
    code_folding: hide
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
params:
  db_account: rogilmore@psu.edu
  update_gs: yes
  update_stats: yes
  vols_to_test: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

# Install packages if needed
cran_packages <- c('ggplot2', 'tidyverse', 'reshape2', 'cowplot',
                    'googledrive', 'plyr', 'googlesheets', 'ezknitr')
not_installed <- cran_packages[!(cran_packages %in% installed.packages()[,"Package"])]
if(length(not_installed)) {
  message('Installing packages required for this document.')
  install.packages(not_installed)
}

github_packages <- 'PLAY-behaviorome/databraryapi'
not_installed <- github_packages[!(github_packages %in% installed.packages()[,"Package"])]
if(length(not_installed)) devtools::install_github(not_installed)

# Load

#library(ezknitr)
#library(rmarkdown)
library(databraryapi)
library(tidyverse)
library(reshape2)
library(cowplot)
#library(googledrive)
  #drive_auth(use_oob = TRUE)
library(plyr)
library(dplyr)
library(googlesheets) 
  options(httr_oob_default=TRUE) 
library(kableExtra)

# Log in to Databrary
if (!databraryapi::login_db(params$db_account)) {
  message("Log-in failed.")
}

# Graphic theme elements
ln_size <- 3
base_size <- 14
color_orange <- "#ec7751"
color_teal <- "#4CAE99"
color_purple <-"#AB00FF"

databrary_theme <- 
  theme_classic(base_size = base_size) +
  theme(axis.title.x=element_blank()) +
  theme(legend.position="none", 
        axis.text = element_text(size = rel(0.8), colour = "black")) +
  theme(axis.line = element_blank()) +
  theme(plot.title = element_text(hjust = 0.5))
```

<!-- # Get Data -->

```{r get-databrary-stats}
new_stats <- databraryapi::get_db_stats()
new_stats$date <- lubridate::as_datetime(new_stats$date)
```

```{r data-from-googlesheets}
#key <- "1tvlIQzULrMtXo97aJu71ljdTmNXkwwpU9eOOasVer3g"
db <- gs_title('Databrary-analytics')
```

```{r load-inst-invest-from-googlesheets}
old_stats <- db %>%
  gs_read(ws = 'institutions-investigators')
```
```{r load-citations-from-googlesheets}
old_citations <- db %>%
  gs_read(ws = 'citations-monthly')
```

# Institutions & Authorized Users 

```{r child = 'users.Rmd'}
```

## New Institutions

```{r child = 'institutions.Rmd'}
```

## New Authorized Investigators

```{r child = 'people.Rmd'}
```

# Volumes

```{r child = 'volumes_shared.Rmd'}
```

<!-- ## Sharing type and session data -->

<!-- ```{r child = 'shared-volumes-sessions.Rmd'} -->
<!-- ``` -->

# Citations

```{r child = 'citations.Rmd'}
```

<!-- # Affiliates -->

<!-- ```{r child = 'affiliates.Rmd'} -->
<!-- ``` -->

<!-- # Copy and Move Report -->
<!-- # ```{r} -->
<!-- # copy_move_rpt() -->
<!-- # ``` -->
