---
title: "Authorized Institutions and Investigators"
author: "Andrea Seisler"
date:  "`r Sys.time()`"
---

```{r}
new_stats <- databraryapi::get_db_stats()
new_stats$date <- lubridate::as_datetime(new_stats$date)

new_stats <- new_stats %>%
  dplyr::select(date, institutions, investigators, affiliates) %>%
  dplyr::mutate(date = lubridate::as_datetime(date))
if (purrr::is_empty(new_stats)) {
  stop("Unable to retrieve new statistics from Databrary.")
}
```


```{r read-old-investigator-institution-data}
if (params$from_gs) {
  db <- googlesheets::gs_title('Databrary-analytics')
  
  old_stats <- db %>%
    googlesheets::gs_read(ws = 'institutions-investigators')
} else {
  old_stats <- readr::read_csv("csv/institutions-investigators.csv")
}
old_stats <- old_stats %>%
  dplyr::mutate(., date = lubridate::as_datetime(date))
```

```{r update-user-stats}
 # initialize updated_stats
updated_stats <- old_stats
if (as.logical(params$update_stats)) {
  next_entry <- dim(updated_stats)[1] + 1
  updated_stats[next_entry, ] = NA
  
  # fill with new data
  # updated_stats$date[next_entry] <- new_stats$date
  # updated_stats$institutions[next_entry] <- new_stats$investigators
  # updated_stats$investigators[next_entry] <- new_stats$investigators
  # updated_stats$affiliates[next_entry] <- new_stats$affiliates
  updated_stats[next_entry, ] <- new_stats
}

# Calculate change
n_rows <- dim(updated_stats)[1]

delta_investigators <- updated_stats$investigators[n_rows] - updated_stats$investigators[n_rows - 1]

delta_institutions <- updated_stats$institutions[n_rows] - updated_stats$institutions[n_rows - 1]
 
# filter NAs
updated_stats <- updated_stats %>%
  dplyr::filter(., !is.na(affiliates),
         !is.na(investigators),
         !is.na(affiliates),
         !is.na(date))
```

<!-- Now, we plot the data. -->

```{r db-inst-user-plot}
# Create a tidy form for plotting both institutions and investigators and affiliates
gathered_stats <- updated_stats %>%
  tidyr::gather(., key = "type", value = "count", -date) %>%
  dplyr::mutate(date = lubridate::as_date(date)) %>%
  dplyr::select(date, count, type) %>%
  dplyr::filter(type %in% c('institutions', 'investigators')) %>%
  dplyr::filter(!is.na(count))

# Plot
users_plot <- gathered_stats %>%
  ggplot(., aes(
    x = date,
    y = count,
    color = type,
    group = type
  )) +
  scale_x_date(date_labels = "%Y", date_breaks = '1 year') +
  geom_point() +
  geom_line(size = ln_size) +
  scale_colour_manual(values = c(color_orange, color_teal)) +
  ggtitle(paste("Authorizations as of ", Sys.Date())) +
  ylab("Authorizations") +
  databrary_theme +
  scale_y_continuous(breaks = seq(0, plyr::round_any(max(
    gathered_stats$count
  ), 100, ceiling), 100), expand = c(0, 0)) +
  coord_cartesian(ylim = c(0, plyr::round_any(max(
    gathered_stats$count
  ), 100, ceiling)))

cowplot::ggdraw(users_plot) +
  cowplot::draw_label(paste0(
    "Investigators: ", updated_stats$investigators[n_rows],
    " (+ ", delta_investigators, ")"), colour = color_teal, .65, .8) +
  cowplot::draw_label(paste0(
    "Institutions: ", updated_stats$institutions[n_rows],
    " (+ ", delta_institutions, ")"), colour = color_orange, .75, .5)
```
<!-- Next, we update the Google Sheet if `params$update_gs` is TRUE. -->
<!-- In the current context, `params$update_gs` == `r params$update_gs`. -->

```{r update-inst-inv-gs}
if (as.logical(params$update_gs)) {
  db <- db %>%
    gs_add_row(ws = 'institutions-investigators', 
               input = new_stats)
  message("'update_gs' parameter is 'TRUE', so Google Sheet data will be updated.")
} else {
  message("'update_gs' parameter is 'FALSE', so Google Sheet data unmodified.")
}
```

```{r update-inst-inv-csv}
if (as.logical(params$update_csv)) {
  if (!purrr::is_empty(updated_stats)) {
  readr::write_csv(updated_stats, "csv/institutions-investigators.csv")
  message("Updated 'csv/institutions-investigators.csv'.")    
  } else {
    message("No new institutions or investigator data to write.")
  }
}
```

