---
title: "citations.Rmd"
author: "Andrea Seisler"
date:  "`r Sys.time()`"
---

<!-- # Citation counts -->

```{r}
if (params$from_gs) {
} else {
  old_citations <- readr::read_csv("../csv/citations-monthly.csv", show_col_types = FALSE)
}

old_citations <- old_citations %>%
  dplyr::mutate(date = lubridate::as_date(date))
```

```{r get-new-citations}
# Get citation counts from Google Scholar
get_citation_stats <- function(project = 'databrary') {
  if (project %in% c('databrary', 'Databrary')) {
    url <-
      'https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22databrary%22+%22Databrary%22&btnG='
  } else if (project %in% c('datavyu', 'Datavyu')) {
    url <-
      'https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22Datavyu%22+%22datavyu%22&btnG='
  }
  
  r <- httr::GET(url = url)
  if (httr::status_code(r) == 200) {
    content <- httr::content(r, 'text')
  } else {
    message(paste0('Download Failed, HTTP status ', httr::status_code(r)))
  }
  
  n_results <-
    stringr::str_match(content, pattern = "About ([0-9]+)")[2]
  if (is.null(n_results)) {
    message(paste0('Unable to parse results from search.'))
    return(NULL)
  } else {
    return(as.numeric(n_results))
  }
}

databrary_cites <- get_citation_stats('databrary')
datavyu_cites <- get_citation_stats('datavyu')
```

```{r}
# Merge old with new
citations <- old_citations
if (as.logical(params$update_stats)) {
  next_value <- dim(old_citations)[1] + 1
  citations[next_value, ] <- NA
  
  citations$date[next_value] <- lubridate::as_date(Sys.Date())
  citations$databrary_citations[next_value] <- databrary_cites
  citations$datavyu_citations[next_value] <- datavyu_cites
}

# Calculate change
n_rows <- dim(citations)[1]
delta_db_cites <-
  citations$databrary_citations[n_rows] - citations$databrary_citations[n_rows - 1]
delta_dv_cites <-
  citations$datavyu_citations[n_rows] - citations$datavyu_citations[n_rows - 1]

# Filter NAs
citations <- citations %>%
  dplyr::filter(.,!is.na(date),
                !is.na(databrary_citations),
                !is.na(datavyu_citations))
```


```{r db-dv-citations-plot}
gathered_citations <- citations %>%
  tidyr::gather(., key = "type", value = "count", -date)

# Plot
citations_plot <-
  gathered_citations %>%
  ggplot(., aes(
    x = date,
    y = count,
    color = type,
    group = type
  )) +
  geom_point() +
  geom_line(size = ln_size) +
  scale_colour_manual(values = c(color_orange, color_teal)) +
  ggtitle(paste("Citations as of ", Sys.Date())) +
  ylab("Citations") +
  databrary_theme +
  scale_y_continuous(breaks = seq(0, plyr::round_any(
    max(gathered_citations$count),
    100, ceiling
  ), 100),
  expand = c(0, 0)) +
  coord_cartesian(ylim = c(0, plyr::round_any(
    max(gathered_citations$count), 100, ceiling
  )))

cowplot::ggdraw(citations_plot) +
  cowplot::draw_label(
    paste0(
      "Datavyu: ",
      citations$datavyu_citations[n_rows],
      " (+",
      delta_dv_cites,
      ")"
    ),
    colour = color_teal,
    .86,
    .3
  ) +
  cowplot::draw_label(
    paste0(
      "Databrary: ",
      citations$databrary_citations[n_rows],
      " (+",
      delta_db_cites,
      ")"
    ),
    colour = color_orange,
    .7,
    .7
  )
```

Google Scholar Citations for  [Databrary](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C39&q=%22databrary%22+%22Databrary%22&oq=) and [Datavyu](https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22Datavyu%22+%22datavyu%22&btnG=).

```{r update-citations-gs}
if (as.logical(params$update_gs)) {
  # new_data <- citations$date[next_value,]
  # db <- db %>%
  #   googlesheets::gs_add_row(ws = 'citations-monthly', 
  #                            input = new_data)
  # message("'update_gs' parameter is 'TRUE', so Google Sheet data will be updated.")
} else {
  message("'update_gs' parameter is 'FALSE', so Google Sheet data unmodified.")
}
```

```{r update-citations-csv}
if (as.logical(params$update_csv)) {
  if (!(is_empty(citations))) {
    readr::write_csv(citations, "../csv/citations-monthly.csv")
    message("Updated '../csv/citations-monthly.csv'.")    
  } else {
    message("No new citations data to write.")
  }
}
```