---
title: "Authorized Institutions and Investigators"
author: "Andrea Seisler & Rick Gilmore"
---


```{r}
targets::tar_load(inst_invest_csv, store = '../../_targets/')
updated_stats <- inst_invest_csv
```

```{r}
# Calculate change
n_rows <- dim(updated_stats)[1]

delta_investigators <- updated_stats$investigators[n_rows] - updated_stats$investigators[n_rows - 1]

delta_institutions <- updated_stats$institutions[n_rows] - updated_stats$institutions[n_rows - 1]
 
# filter NAs
updated_stats <- updated_stats %>%
  dplyr::filter(., !is.na(affiliates),
         !is.na(investigators),
         !is.na(affiliates),
         !is.na(date))
```

<!-- Now, we plot the data. -->

```{r}
# Create a tidy form for plotting both institutions and investigators and affiliates
gathered_stats <- updated_stats %>%
  tidyr::gather(., key = "type", value = "count", -date) %>%
  dplyr::mutate(date = lubridate::as_date(date)) %>%
  dplyr::select(date, count, type) %>%
  dplyr::filter(type %in% c('institutions', 'investigators')) %>%
  dplyr::filter(!is.na(count))

# Plot
users_plot <- gathered_stats %>%
  ggplot(., aes(
    x = date,
    y = count,
    color = type,
    group = type
  )) +
  scale_x_date(date_labels = "%Y", date_breaks = '1 year') +
  geom_point() +
  geom_line(linewidth = ln_size) +
  scale_colour_manual(values = c(color_orange, color_teal)) +
  ggtitle(paste("Authorizations as of ", Sys.Date())) +
  ylab("Authorizations") +
  databrary_theme +
  scale_y_continuous(breaks = seq(0, plyr::round_any(max(
    gathered_stats$count
  ), 100, ceiling), 100), expand = c(0, 0)) +
  coord_cartesian(ylim = c(0, plyr::round_any(max(
    gathered_stats$count
  ), 100, ceiling)))

cowplot::ggdraw(users_plot) +
  cowplot::draw_label(paste0(
    "Investigators: ", updated_stats$investigators[n_rows],
    " (+ ", delta_investigators, ")"), colour = color_teal, .65, .8) +
  cowplot::draw_label(paste0(
    "Institutions: ", updated_stats$institutions[n_rows],
    " (+ ", delta_institutions, ")"), colour = color_orange, .75, .5)
```


