---
title: "Shared volumes"
author: "Andrea Seisler"
date:  "`r Sys.time()`"
---


```{r get-new-db-stats}
new_stats <- databraryapi::get_db_stats()
new_stats$date <- lubridate::as_datetime(new_stats$date)
```

```{r, load-volumes-data}
if (params$from_gs) {
} else {
  old_vols <- readr::read_csv("../csv/volumes-shared-unshared.csv", show_col_types = FALSE)
}

if (purrr::is_empty(old_vols)) {
  stop("No old data loaded.")
}
```

```{r update-volumes-data}
# Filter NAs
updated_vols <- old_vols %>%
  dplyr::filter(., !is.na(shared_volumes),
                !is.na(unshared_volumes),
                !is.na(date))  

if (as.logical(params$update_stats)) {
  next_entry <- dim(updated_vols)[1] + 1
  updated_vols[next_entry,] = NA
  
  updated_vols$date[next_entry] <- new_stats$date
  if (is.null(new_stats$datasets_shared)) {
    new_stats$datasets_shared = 0
  }
  updated_vols$shared_volumes[next_entry] <- new_stats$datasets_shared
  updated_vols$unshared_volumes[next_entry] <- 
    new_stats$datasets_total - new_stats$datasets_shared
}


# Calculate change
n_rows <- dim(updated_vols)[1]

delta_shared <- updated_vols$shared_volumes[n_rows] - updated_vols$shared_volumes[n_rows - 1]

delta_unshared <- updated_vols$unshared_volumes[n_rows] - updated_vols$unshared_volumes[n_rows - 1]

updated_vols <- updated_vols %>%
  dplyr::filter(., !is.na(shared_volumes),
                !is.na(unshared_volumes),
                !is.na(date))

gathered_vols <- updated_vols %>%
  tidyr::gather(., key = "type", value = "count", -date)
```

```{r db-vols-plot}
# Plot
vols_plot <- gathered_vols %>%
  ggplot(., aes(
    x = date,
    y = count,
    color = type,
    group = type
  )) +
  geom_point() +
  geom_line(size = ln_size) +
  scale_colour_manual(values = c(color_orange, color_teal)) +
  ggtitle(paste("Volumes as of ", Sys.Date())) +
  ylab("Volumes") +
  databrary_theme +
  scale_y_continuous(breaks = seq(0, plyr::round_any(max(
    gathered_vols$count
  ),
  100, ceiling), 100),
  expand = c(0, 0)) +
  coord_cartesian(ylim = c(0, plyr::round_any(max(
    gathered_vols$count
  ),
  100, ceiling)))

cowplot::ggdraw(vols_plot) +
  cowplot::draw_label(
    paste0(
      "Unshared: ",
      updated_vols$unshared_volumes[n_rows],
      " (+",
      delta_unshared,
      ")"
    ),
    colour = color_teal,
    .6,
    .85
  ) +
  cowplot::draw_label(
    paste0(
      "Shared: ",
      updated_vols$shared_volumes[n_rows],
      " (+",
      delta_shared,
      ")"
    ),
    colour = color_orange,
    .75,
    .50
  )
```


```{r update-vols-shared-unshared-gs}
if (as.logical(params$update_gs)) {
  db <- db %>%
    gs_add_row(ws = 'volumes-shared-unshared', input = updated_vols)
} else {
  message("'update_gs' parameter is 'false', so Google Sheet data unmodified.")
}
```

```{r update-vols-shared-unshared-csv}
if (as.logical(params$update_csv)) {
  if (!is_empty(updated_vols)) {
    readr::write_csv(updated_vols, "../csv/volumes-shared-unshared.csv")
    message("Updated '../csv/volumes-shared-unshared.csv'.")    
  } else {
    message("No new volumes data to write.")
  }
}
```

## New volumes {-}

```{r new-volumes}
# define helper functions
new_volumes <- databraryapi::get_db_stats(type = "datasets")
if (is.null(new_volumes)) {
  stop('New volumes data not downloaded.')
}
```


```{r}
unnested_vols <- new_volumes %>%
  dplyr::rename(vol_id = id, vol_name = name) %>%
  tidyr::unnest(., cols = c(owners))
```

```{r}
unnested_vols <- unnested_vols %>%
  dplyr::mutate(
    .,
    url = paste0("https://nyu.databrary.org/volume/", vol_id),
    date_created = lubridate::as_date(creation)
  )
```

```{r}
unnested_vols %>%
  dplyr::select(., vol_name, date_created, name, url) %>%
  knitr::kable(col.names = c("Volume Name", "Date Created", "Owner Name", "Databrary URL"), "html") %>%
  kableExtra::kable_styling(.)
```

<!-- ## Shared volumes -->

<!-- ### Full volume -->

<!-- ### Overview only -->
