# Weekly

## Set-up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

source("R/helpers.R")
##install_required_pkgs()

# Log in to Databrary
if (!databraryapi::login_db(params$db_account)) {
  message("Log-in failed.")
} else {
  message("Log-in succeeded.")
}

# Add pipe operator to workspace via tidyverse
library(tidyverse)

# Graphic theme elements
ln_size <- 3
base_size <- 14
color_orange <- "#ec7751"
color_teal <- "#4CAE99"
color_purple <-"#AB00FF"

databrary_theme <- 
  ggplot2::theme_classic(base_size = base_size) +
  ggplot2::theme(axis.title.x = ggplot2::element_blank()) +
  ggplot2::theme(legend.position="none", 
        axis.text = ggplot2::element_text(size = ggplot2::rel(0.8), colour = "black")) +
  ggplot2::theme(axis.line = ggplot2::element_blank()) +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
```

## Institutions & Authorized Users 

```{r child = 'rmd/users.Rmd'}
```

### New Institutions

```{r child = 'rmd/institutions.Rmd'}
```

### New and Updated Authorized Investigators

```{r child = 'rmd/people.Rmd'}
```

## Volumes

```{r child = 'rmd/volumes_shared.Rmd'}
```

## Citations

```{r child = 'rmd/citations.Rmd'}
```

## Archived reports

```{r child = 'rmd/old_weekly_reports.Rmd'}
```

## Clean-up

```{r clean-up, include=FALSE}
databraryapi::logout_db()
if (file.exists(".databrary.RData")) {
  unlink(".databrary.RData")
}
```

