# Assets

## Purpose

This report summarizes the types of files (assets) that are stored and shared.

## Import

```{r, message=FALSE, echo=TRUE}
library(targets)
tar_load(volume_asset_stats_df, store = "../_targets/")
```

## Analyze

### Volumes with shared assets

There are `r length(unique(volume_asset_stats_df$vol_id))` shared volumes with assets.

The following shows the number of shared volumes with a given asset type.

```{r, echo=TRUE}
volume_asset_stats_df %>%
  dplyr::group_by(asset_type) %>%
  dplyr::count(asset_type) %>%
  dplyr::arrange(., desc(n)) %>%
  kableExtra::kable(., format = 'html') %>%
  kableExtra::kable_styling(.)
```

### Assets

Total number of assets, total size, and total duration by type:

```{r, echo=TRUE}
volume_asset_stats_df %>%
  dplyr::group_by(asset_type) %>%
  dplyr::summarise(total_files = sum(n_files),
            total_size = sum(tot_size_gb),
            total_dur = sum(tot_dur_hrs)) %>%
  dplyr::arrange(., desc(total_files)) %>%
  dplyr::select(asset_type, total_files, total_size, total_dur) %>%
  kableExtra::kable(., format = 'html') %>%
  kableExtra::kable_styling(.)
```

